/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.williamgrose.android.songscribbler;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int body=0x7f050002;
        public static final int chords=0x7f050001;
        public static final int scroll_body=0x7f050005;
        public static final int scroll_chords=0x7f050003;
        public static final int scroll_speed=0x7f050004;
        public static final int textRow=0x7f050006;
        public static final int title=0x7f050000;
    }
    public static final class layout {
        public static final int song_edit=0x7f030000;
        public static final int song_view=0x7f030001;
        public static final int songs_list=0x7f030002;
        public static final int songs_row=0x7f030003;
    }
    public static final class string {
        public static final int activity_edit_name=0x7f040001;
        public static final int activity_list_name=0x7f040000;
        public static final int activity_view_name=0x7f040002;
        public static final int edit_body=0x7f04000a;
        public static final int edit_chords=0x7f040009;
        public static final int edit_song=0x7f04000b;
        public static final int edit_title=0x7f040008;
        public static final int menu_delete=0x7f040005;
        public static final int menu_insert=0x7f040004;
        public static final int menu_save=0x7f040006;
        public static final int menu_scroll_reset=0x7f04000e;
        public static final int menu_scroll_start=0x7f04000c;
        public static final int menu_scroll_stop=0x7f04000d;
        public static final int menu_view=0x7f040007;
        public static final int no_songs=0x7f040003;
        public static final int scroll_speed=0x7f04000f;
        public static final int scroll_speed_prompt=0x7f040010;
    }
}
